### ISSUE TITLE
No response on some of the leveling cmds + Suggestions

### ISSUE THREAD

**Issue by HaniXP** [No1IrishStig/Devolution-Beta#2]
leveling toggle
toggle messages

----------------

These commands dont send out any response when entering them, & if they dont give any response then i wouldnt know if i disabled leveling or not.

----------------------------------------------------------

Suggestions :-

- Add Help descriptions to every command (i.e : !help about)
- Add Few more features to "!say" command (i.e as suggested in discord, something like !say [channel name] Hello !

**Comment by No1IrishStig** [comment]
Help descriptions, may be added in future when I get a chance.

See v1.9 as the !say feature is added as well as the leveling not giving any response. 

Have fun!
